
name: ci/cd pipeline
#what will trigger the pipeline here we just choose push 
on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
#the label of our runner
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
